function defaultOptions = clustheat_defaults()
    defaultOptions.trialstart = 1;
    defaultOptions.trialend = 20;
    defaultOptions.binsiz = 5;
    defaultOptions.pre_start = 41;
    defaultOptions.pre_end = 45;
    defaultOptions.od_start = 51;
    defaultOptions.od_end = 75;
    defaultOptions.post_start = 76;
    defaultOptions.post_end = 85;
    defaultOptions.norm_type = 'zscore';
    defaultOptions.baseline_sub = true;
    defaultOptions.numclust = 5;
    defaultOptions.method = 'ward';
    defaultOptions.metric = 'euclidean';
    defaultOptions.odord = [5,1,3,6,2,4];
    defaultOptions.odnames = ["TMT","4MT","IAA","Hep","Nut","2PE"];
    defaultOptions.cmin = -1.5;
    defaultOptions.cmax = 3;
end